version: "3.9"


services:
  golang_app:
  container_name: golang_app
  db_postgres:
    container_name: db_postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}
