version: "3.8"

services:
  golang_app:
    container_name: golang_app
    build: .
    environment:
      DATABASE_HOST: db_postgres  
      DATABASE_PORT: 5432
      DATABASE_USER: test_user    
      DATABASE_PASS: test_pass    
      DATABASE_NAME: test_db      
      AUTH_DURATION_MINUTES: 1   
      AUTH_SECRET: your_strong_secret_key  
      AUTH_WEBHOOK_IP: ""         
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db_postgres:
        condition: service_healthy
    restart: on-failure
  db_postgres:
    container_name: db_postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:  
  pgdata: {}
