basePath: /
definitions:
  models.AuthSwag:
    properties:
      uuid:
        example: uuid
        type: string
    required:
    - uuid
    type: object
  models.RefreshSwag:
    properties:
      jwt:
        example: jwt
        type: string
      refresh:
        example: refresh
        type: string
    required:
    - jwt
    - refresh
    type: object
info:
  contact: {}
  title: auth service for medods
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login form
        in: body
        name: Data
        required: true
        schema:
          $ref: '#/definitions/models.AuthSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Login
      tags:
      - AUTH
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: refresh form
        in: body
        name: Data
        required: true
        schema:
          $ref: '#/definitions/models.RefreshSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Refresh
      tags:
      - AUTH
  /data/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - USER
  /data/me/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get user's UUID
      tags:
      - USER
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
